AllCops:
  DisplayCopNames: true
  Exclude:
    - ".bundle/**/*"
    - ".kitchen/**/*"
    - "vendor/**/*"

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 80
  Exclude:
    - "**/attributes/*.rb"
    - "**/metadata.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%r": "()"
    "%w": "[]"  # Arrays use brackets
    "%W": "[]"  # Arrays use brackets
