language: ruby
bundler_args: --jobs 4 --without integration
rvm:
  - 2.3.1
cache: bundler
sudo: false  # travis docker container
env:
  matrix:
    - CHEF_VERSION=12.5.0
    - CHEF_VERSION=12.18.31
before_script:
  - "gem install bundler-audit --no-rdoc --no-ri && bundle-audit update"
script:
  - bundle-audit check --ignore OSVDB-117461 CVE-2015-1820
  - bundle exec rake license_finder
  - bundle exec rake rubocop
  - bundle exec rake foodcritic
  - bundle exec rake chefspec
  - bundle exec rake kitchen:all
